[package]
name = "sbi-n/react-base-components"
version = "0.1.7"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"
realm = "shared"

[dependencies]
react = "jsdotlua/react@^17.2.1"